import { useEffect, useMemo, useState } from "react";
import { supabase } from "./supabaseClient";
const PURPLE="#8e24aa",INK="#13243b",MUTED="#627187",LINE="#dfe7ef",SOFT="#f6f9fc";
const input={height:38,borderRadius:9,border:`1px solid ${LINE}`,padding:"0 10px",fontSize:11,background:"#fff"};
const button=(p=false)=>({height:38,borderRadius:9,border:p?0:`1px solid ${LINE}`,padding:"0 13px",fontSize:11,fontWeight:800,background:p?PURPLE:"#fff",color:p?"#fff":INK,cursor:"pointer"});
const fmt=v=>new Date(v).toLocaleString("en-IE",{weekday:"short",day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"});
export default function CoachCalendar({club,selectedTeam,currentUserId}){
 const [events,setEvents]=useState([]),[sessions,setSessions]=useState([]),[players,setPlayers]=useState([]),[responses,setResponses]=useState([]),[attendance,setAttendance]=useState([]),[message,setMessage]=useState("");
 const [showAdd,setShowAdd]=useState(false),[opponent,setOpponent]=useState(""),[location,setLocation]=useState(""),[startsAt,setStartsAt]=useState(""),[endsAt,setEndsAt]=useState("");
 async function load(){if(!selectedTeam?.id)return;const [e,s,p]=await Promise.all([supabase.from("club_events").select("*,facility:facilities(name)").eq("age_group_id",selectedTeam.id).order("starts_at"),supabase.from("sessions").select("*,plan:weekly_plans(age_group_id)").eq("plan.age_group_id",selectedTeam.id).order("session_date",{ascending:false}).limit(40),supabase.from("journey_players").select("id,name").eq("age_group_id",selectedTeam.id).order("name")]);setEvents(e.data||[]);setSessions((s.data||[]).filter(x=>x.plan?.age_group_id===selectedTeam.id));setPlayers(p.data||[]);const ids=(e.data||[]).map(x=>x.id);if(ids.length){const [r,a]=await Promise.all([supabase.from("availability_responses").select("*").in("event_id",ids),supabase.from("event_attendance").select("*").in("event_id",ids)]);setResponses(r.data||[]);setAttendance(a.data||[]);}else{setResponses([]);setAttendance([]);}}
 useEffect(()=>{load();},[selectedTeam?.id]);
 async function addMatch(){if(!opponent.trim()||!startsAt){setMessage("Add opponent and match time.");return;}const end=endsAt||new Date(new Date(startsAt).getTime()+75*60000).toISOString();const {data,error}=await supabase.from("club_events").insert({club_id:club.id,age_group_id:selectedTeam.id,event_type:"match",title:`Match vs ${opponent.trim()}`,opponent:opponent.trim(),location:location.trim()||null,starts_at:startsAt,ends_at:end,status:"scheduled",source:"coach",created_by:currentUserId,response_deadline:new Date(new Date(startsAt).getTime()-24*3600000).toISOString()}).select().single();if(error){setMessage(error.message);return;}const {data:kids}=await supabase.from("journey_players").select("parent_user_id").eq("age_group_id",selectedTeam.id).not("parent_user_id","is",null);const unique=[...new Set((kids||[]).map(x=>x.parent_user_id).filter(Boolean))];if(unique.length)await supabase.from("notifications").insert(unique.map(uid=>({club_id:club.id,user_id:uid,age_group_id:selectedTeam.id,event_id:data.id,type:"match_added",title:"New match added",message:`${data.title} · ${fmt(data.starts_at)}${location?` · ${location}`:""}. Please confirm availability in Spraoi.`,priority:"important",action_url:"/"})));setOpponent("");setLocation("");setStartsAt("");setEndsAt("");setShowAdd(false);setMessage("Match added and parents notified in Spraoi.");load();}
 async function markAttendance(event,playerId,status){await supabase.from("event_attendance").upsert({event_id:event.id,player_id:playerId,status,marked_by:currentUserId,marked_at:new Date().toISOString(),source:"coach"},{onConflict:"event_id,player_id"});load();}
 async function remindNonResponders(event){
    const eventResponses=responses.filter(r=>r.event_id===event.id);
    const respondedPlayers=new Set(eventResponses.map(r=>r.player_id));
    const missingPlayers=players.filter(p=>!respondedPlayers.has(p.id));
    if(!missingPlayers.length){setMessage("Everyone has responded for this match.");return;}
    const {data:kids}=await supabase.from("journey_players").select("id,parent_user_id").in("id",missingPlayers.map(p=>p.id)).not("parent_user_id","is",null);
    const parentIds=[...new Set((kids||[]).map(x=>x.parent_user_id).filter(Boolean))];
    if(parentIds.length) await supabase.from("notifications").insert(parentIds.map(uid=>({club_id:club.id,user_id:uid,age_group_id:selectedTeam.id,event_id:event.id,type:"availability_reminder",title:"Availability reminder",message:`Please confirm availability for ${event.title} on ${fmt(event.starts_at)}.`,priority:"important",action_url:"/"})));
    setMessage(`${parentIds.length} parent reminder${parentIds.length===1?"":"s"} added in Spraoi.`);
  }
 async function cancelEvent(event){await supabase.from("club_events").update({status:"cancelled",updated_at:new Date().toISOString()}).eq("id",event.id);const {data:kids}=await supabase.from("journey_players").select("parent_user_id").eq("age_group_id",selectedTeam.id).not("parent_user_id","is",null);const unique=[...new Set((kids||[]).map(x=>x.parent_user_id).filter(Boolean))];if(unique.length)await supabase.from("notifications").insert(unique.map(uid=>({club_id:club.id,user_id:uid,age_group_id:selectedTeam.id,event_id:event.id,type:"event_cancelled",title:"Team event cancelled",message:`${event.title} on ${fmt(event.starts_at)} has been cancelled.`,priority:"important"})));load();}
 const discrepancies=sessions.map(sess=>{const ev=events.find(e=>e.session_id===sess.id||e.id===sess.event_id);if(!ev)return null;const plannedTime=sess.planned_starts_at?new Date(sess.planned_starts_at).getTime():null;const officialTime=new Date(ev.starts_at).getTime();const timeDiff=plannedTime&&Math.abs(plannedTime-officialTime)>5*60000;const locationDiff=sess.planned_location&&String(sess.planned_location).trim().toLowerCase()!==String(ev.facility?.name||ev.location||"").trim().toLowerCase();return (timeDiff||locationDiff)?{sess,ev,timeDiff,locationDiff}:null;}).filter(Boolean);
 const upcoming=events.filter(e=>new Date(e.starts_at)>new Date(Date.now()-3*3600000));const past=events.filter(e=>new Date(e.starts_at)<=new Date(Date.now()-3*3600000)).reverse();
 return <div style={{flex:1,overflow:"auto",background:SOFT,padding:22}}><div style={{maxWidth:1100,margin:"0 auto"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,marginBottom:16}}><div><h1 style={{margin:0,fontSize:24,color:INK}}>Team Calendar</h1><div style={{fontSize:11,color:MUTED,marginTop:4}}>Training allocations, matches, availability and attendance.</div></div><button onClick={()=>setShowAdd(v=>!v)} style={button(true)}>+ Add match</button></div>{message&&<div style={{background:"#fff",border:`1px solid ${LINE}`,borderRadius:12,padding:11,marginBottom:12,fontSize:11}}>{message}</div>}{showAdd&&<div style={{background:"#fff",border:`1px solid ${LINE}`,borderRadius:16,padding:16,marginBottom:14}}><b>Add match</b><div style={{display:"grid",gridTemplateColumns:"1.3fr 1.3fr 1fr 1fr auto",gap:8,marginTop:10}}><input value={opponent} onChange={e=>setOpponent(e.target.value)} placeholder="Opponent" style={input}/><input value={location} onChange={e=>setLocation(e.target.value)} placeholder="Venue / location" style={input}/><input type="datetime-local" value={startsAt} onChange={e=>setStartsAt(e.target.value)} style={input}/><input type="datetime-local" value={endsAt} onChange={e=>setEndsAt(e.target.value)} style={input}/><button onClick={addMatch} style={button(true)}>Save</button></div></div>}
 {discrepancies.length>0&&<div style={{background:"#fff7ed",border:"1px solid #fdba74",borderRadius:16,padding:16,marginBottom:14}}><b style={{color:"#9a3412"}}>Plan needs review</b><div style={{fontSize:10,color:"#9a3412",marginTop:3}}>A Coach plan differs from the Club-confirmed time or venue. Nothing has been overwritten.</div><div style={{display:"grid",gap:8,marginTop:10}}>{discrepancies.map(({sess,ev})=><div key={sess.id} style={{background:"#fff",border:"1px solid #fed7aa",borderRadius:10,padding:11}}><div style={{fontSize:11,fontWeight:800}}>Coach plan: {sess.planned_starts_at?fmt(sess.planned_starts_at):"Time TBC"} · {sess.planned_location||"Location TBC"}</div><div style={{fontSize:11,color:"#9a3412",marginTop:3}}>Club confirmed: {fmt(ev.starts_at)} · {ev.facility?.name||ev.location||"Location TBC"}</div><button onClick={async()=>{await supabase.from("sessions").update({planned_starts_at:ev.starts_at,planned_ends_at:ev.ends_at,planned_location:ev.facility?.name||ev.location||null}).eq("id",sess.id);setMessage("Coach plan updated to the Club allocation.");load();}} style={{...button(true),marginTop:8}}>Use club allocation</button></div>)}</div></div>}
 <div style={{background:"#fff",border:`1px solid ${LINE}`,borderRadius:16,padding:16,marginBottom:14}}><b>Upcoming</b><div style={{display:"grid",gap:8,marginTop:10}}>{upcoming.length===0&&<span style={{fontSize:11,color:MUTED}}>No upcoming events.</span>}{upcoming.map(e=>{const yes=responses.filter(r=>r.event_id===e.id&&r.response==="yes").length,no=responses.filter(r=>r.event_id===e.id&&r.response==="no").length;return <div key={e.id} style={{border:`1px solid ${LINE}`,borderRadius:11,padding:12,display:"flex",justifyContent:"space-between",gap:12}}><div><b>{e.event_type==="match"?(e.opponent?`Match vs ${e.opponent}`:"Match"):"Training"}</b><div style={{fontSize:10,color:MUTED,marginTop:3}}>{fmt(e.starts_at)} · {e.facility?.name||e.location||"Location TBC"}</div>{e.event_type==="match"&&<div style={{fontSize:10,color:MUTED,marginTop:4}}>Availability: {yes} yes · {no} no · {Math.max(players.length-yes-no,0)} awaiting</div>}</div><div style={{display:"flex",gap:6}}>{e.event_type==="match"&&e.status!=="cancelled"&&<button onClick={()=>remindNonResponders(e)} style={button(false)}>Remind</button>}<button onClick={()=>cancelEvent(e)} disabled={e.status==="cancelled"} style={button(false)}>{e.status==="cancelled"?"Cancelled":"Cancel"}</button></div></div>})}</div></div>
 <div style={{background:"#fff",border:`1px solid ${LINE}`,borderRadius:16,padding:16,marginBottom:14}}><b>Attendance report</b><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:8,marginTop:10}}>{players.map(p=>{const relevant=events.filter(e=>new Date(e.starts_at)<new Date());const training=relevant.filter(e=>e.event_type==="training"),matches=relevant.filter(e=>e.event_type==="match");const pct=(list)=>{if(!list.length)return "—";const present=list.filter(e=>["present","late"].includes(attendance.find(a=>a.event_id===e.id&&a.player_id===p.id)?.status)).length;return `${Math.round(present/list.length*100)}%`;};return <div key={p.id} style={{border:`1px solid ${LINE}`,borderRadius:10,padding:10}}><div style={{fontSize:11,fontWeight:900}}>{p.name}</div><div style={{fontSize:9,color:MUTED,marginTop:4}}>Training {pct(training)} · Matches {pct(matches)} · Overall {pct(relevant)}</div></div>})}</div></div>
 <div style={{background:"#fff",border:`1px solid ${LINE}`,borderRadius:16,padding:16}}><b>Attendance to complete</b><div style={{fontSize:10,color:MUTED,marginTop:3}}>After every training session or match, confirm who actually attended.</div><div style={{display:"grid",gap:10,marginTop:12}}>{past.slice(0,8).map(e=>{const marked=attendance.filter(a=>a.event_id===e.id).length;return <details key={e.id} style={{border:`1px solid ${marked>=players.length&&players.length?"#86efac":LINE}`,borderRadius:11,padding:12}}><summary style={{cursor:"pointer",fontWeight:800,fontSize:11}}>{marked>=players.length&&players.length?"✓ ":"⚠ "}{e.title} · {fmt(e.starts_at)} — {marked}/{players.length} marked</summary><div style={{display:"grid",gap:6,marginTop:10}}>{players.map(p=>{const a=attendance.find(x=>x.event_id===e.id&&x.player_id===p.id);return <div key={p.id} style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:8}}><span style={{fontSize:11}}>{p.name}</span><div style={{display:"flex",gap:4}}>{[["present","Present"],["absent","Absent"],["late","Late"],["excused","Excused"]].map(([v,l])=><button key={v} onClick={()=>markAttendance(e,p.id,v)} style={{padding:"5px 7px",borderRadius:7,border:`1px solid ${a?.status===v?PURPLE:LINE}`,background:a?.status===v?"#f3e5f5":"#fff",fontSize:9,fontWeight:700}}>{l}</button>)}</div></div>})}</div></details>})}</div></div></div></div>;
}
